name: Surge Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
      - '.github/**'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Install packages
        run: npm install
        working-directory: frontend
      - name: Build the app
        run: npm run build
        working-directory: frontend
      - name: Install Surge
        run: npm install -g surge
      - name: Deploy to surge
        run: surge ./dist corsacOTA.surge.sh --token ${{secrets.SURGE_TOKEN}}
        working-directory: frontend
