name: Example build test

on:
  push:
    paths:
      - 'src/**'
      - 'examples/**'
      - '.github/**'
  pull_request:
    paths:
      - 'src/**'
      - 'examples/**'
      - '.github/**'

jobs:
  esp8266-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: before_install
      run: |
        sudo apt update
        sudo apt install -y gcc git wget make libncurses-dev flex bison python3 python3-serial ninja-build
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        python3 get-pip.py
        wget https://github.com/espressif/ESP8266_RTOS_SDK/releases/download/v3.4/ESP8266_RTOS_SDK-v3.4.zip
        unzip ESP8266_RTOS_SDK-v3.4.zip
        python3 -m pip install --user -r ./ESP8266_RTOS_SDK/requirements.txt

    - name: install
      run: |
        # sudo ./ESP8266_RTOS_SDK/install.sh
        wget https://dl.espressif.com/dl/xtensa-lx106-elf-gcc8_4_0-esp-2020r3-linux-amd64.tar.gz
        tar -xzf xtensa-lx106-elf-gcc8_4_0-esp-2020r3-linux-amd64.tar.gz

    - name: script
      id: script
      run: |
        export PATH="$PATH:$PWD/xtensa-lx106-elf/bin"
        export IDF_PATH=$PWD/ESP8266_RTOS_SDK
        cd examples
        python3 ../ESP8266_RTOS_SDK/tools/idf.py build

  esp32-series-build:
    runs-on: ubuntu-20.04
    continue-on-error: true
    strategy:
      matrix:
        target-hardware: [esp32, esp32c3, esp32s3]
    steps:
    - uses: actions/checkout@v4
    - name: build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4.2
        target: ${{ matrix.target-hardware }}
        path: './examples/'
